import {
  Home,
  Map,
  GraduationCap,
  Calendar,
  MoreHorizontal,
  Users,
  Building2,
  BookOpen,
  Bell,
  Briefcase,
  FlaskConical,
  Lightbulb,
  Globe2,
  Wrench,
  Heart,
  Shield,
  Settings,
  Sparkles,
  Utensils,
  Dumbbell,
  BedDouble,
  Library,
  Activity,
  MessageCircle,
  Star,
  Accessibility,
} from "lucide-react";

export const mobileNav = [
  { href: "/", label: "Home", icon: Home },
  { href: "/map", label: "Map", icon: Map },
  { href: "/academics", label: "Academics", icon: GraduationCap },
  { href: "/events", label: "Events", icon: Calendar },
  { href: "/more", label: "More", icon: MoreHorizontal },
];

export const desktopNav = [
  { href: "/", label: "Home", icon: Home, group: "Core" },
  { href: "/map", label: "Campus Map", icon: Map, group: "Core" },
  { href: "/pulse", label: "Campus Pulse", icon: Activity, group: "Core" },
  { href: "/academics", label: "Academic OS", icon: GraduationCap, group: "Learn" },
  { href: "/schools", label: "Academic Universe", icon: Building2, group: "Learn" },
  { href: "/people", label: "People OS", icon: Users, group: "Learn" },
  { href: "/library", label: "Library", icon: Library, group: "Learn" },
  { href: "/clubs", label: "Clubs", icon: Heart, group: "Life" },
  { href: "/events", label: "Events", icon: Calendar, group: "Life" },
  { href: "/notices", label: "Notices", icon: Bell, group: "Life" },
  { href: "/exams", label: "Exams", icon: BookOpen, group: "Life" },
  { href: "/hostel", label: "Hostel", icon: BedDouble, group: "Campus" },
  { href: "/food", label: "Food", icon: Utensils, group: "Campus" },
  { href: "/sports", label: "Sports & Wellness", icon: Dumbbell, group: "Campus" },
  { href: "/research", label: "Research", icon: FlaskConical, group: "Grow" },
  { href: "/innovation", label: "Innovation", icon: Lightbulb, group: "Grow" },
  { href: "/career", label: "Career", icon: Briefcase, group: "Grow" },
  { href: "/global", label: "Global Adamas", icon: Globe2, group: "Grow" },
  { href: "/services", label: "Service Hub", icon: Wrench, group: "Help" },
  { href: "/aura", label: "AURA Assistant", icon: Sparkles, group: "Help" },
  { href: "/safety", label: "Safety", icon: Shield, group: "Help" },
  { href: "/my-campus", label: "My Campus", icon: Star, group: "Me" },
  { href: "/notifications", label: "Notifications", icon: MessageCircle, group: "Me" },
  { href: "/accessibility", label: "Accessibility", icon: Accessibility, group: "Me" },
  { href: "/onboarding", label: "Onboarding", icon: Sparkles, group: "Me" },
  { href: "/admin", label: "Admin CMS", icon: Settings, group: "Admin" },
];

export const moreLinks = desktopNav.filter(
  (i) => !["/", "/map", "/academics", "/events"].includes(i.href)
);
